[build]
  # This tells Netlify *what* to run
  command = "npm run build"
  
  # This tells Netlify *where* to find the finished site
  publish = "build/client" 

[[redirects]]
  # This is the SPA rule that fixes your "Page not found" error
  from = "/*"
  to = "/index.html"
  status = 200
